- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-monasca-pipeline-events from old job
    gate-tempest-dsvm-monasca-pipeline-events-ubuntu-xenial-nv
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=0
          export OVERRIDE_ENABLED_SERVICES=key,mysql,rabbit,tempest,dstat

          devstack_plugin=''
          if [ events == 'logs' ]; then
            devstack_plugin='log-api'
            export DEVSTACK_LOCAL_CONFIG="enable_plugin monasca-log-api git://git.openstack.org/openstack/monasca-log-api"
          elif [ events == 'events' ]; then
            devstack_plugin='events-api'
            export DEVSTACK_LOCAL_CONFIG="enable_plugin monasca-events-api git://git.openstack.org/openstack/monasca-events-api"
          else
            echo "Unknown pipeline events"
            exit 1
          fi

          pre_test_hook_script=$BASE/new/monasca-$devstack_plugin/devstack/pre_test_hook.sh
          post_test_hook_script=$BASE/new/monasca-$devstack_plugin/devstack/post_test_hook.sh
          devstack_rc_script=/opt/stack/new/monasca-$devstack_plugin/devstack/devstackgaterc

          if [ -f $pre_test_hook_script ]; then
              function pre_test_hook {
                  source $pre_test_hook_script
              }
              export -f pre_test_hook
          fi

          if [ -f $post_test_hook_script ]; then
              function post_test_hook {
                  source $post_test_hook_script
              }
              export -f post_test_hook
          fi

          if [ -f $devstack_rc_script ]; then
              export DEVSTACK_GATE_SETTINGS=$devstack_rc_script
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
