- name: Get service-types data file
  uri:
    url: https://service-types.openstack.org/service-types.json
    body_format: json
  register: service_types

- block:
    - name: Set service_type_data fact
      set_fact:
        service_type_data: "{{ service_types['json']['primary_service_by_project'][zuul.project.short_name] }}"
  rescue:
    - name: Handle missing service type mapping
      fail:
        msg: "{{ zuul.project.short_name }} is not mapped in service types"
