- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-sahara from old job gate-tempest-dsvm-sahara-ubuntu-xenial
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin sahara git://git.openstack.org/openstack/sahara
          enable_plugin heat git://git.openstack.org/openstack/heat
          enable_plugin ceilometer git://git.openstack.org/openstack/ceilometer
          TEMPEST_PLUGINS='/opt/stack/new/sahara-tests'

          EOF
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=1
          export KEEP_LOCALRC=1
          export DEVSTACK_GATE_TEMPEST_REGEX="(sahara_tempest_plugin.tests.api|sahara_tempest_plugin.tests.clients|data_processing)"
          export PROJECTS="openstack/sahara $PROJECTS"
          export PROJECTS="openstack/sahara-tests $PROJECTS"

          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          # required at least by client tests (python and CLI)
          function pre_test_hook {
              cd /opt/stack/new/sahara-tests/tools/gate/cli_tests
              ./pre_test_hook.sh
          }

          export -f pre_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
