- hosts: all
  name: Autoconverted job legacy-dib-dsvm-functests-python2-ubuntu-trusty from old
    job gate-dib-dsvm-functests-python2-ubuntu-trusty
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -u
          set -e
          set -x
          cd ~

          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            git://git.openstack.org \
            openstack/diskimage-builder \
            openstack/requirements
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cd ~/openstack/diskimage-builder
          /usr/local/jenkins/slave_scripts/install-distro-packages.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: "set -u\nset -e\nset -x\n#\n# We do things that might exceed the default\
          \ 2GiB tmpfs, and\n# use the larger mounted space.\ncd ~\nsudo mkdir /opt/dib_cache\n\
          sudo chown jenkins:jenkins /opt/dib_cache\nexport DIB_NO_TMPFS=1\nexport\
          \ TMPDIR=/opt/dib_cache\n\nvirtualenv -p python2 env\n\nexport UPPER_CONSTRAINTS_FILE=$(pwd)/openstack/requirements/upper-constraints.txt\n\
          sed -i '/^diskimage-builder/d' $UPPER_CONSTRAINTS_FILE\n./env/bin/pip install\
          \ $(pwd)/openstack/diskimage-builder -c $UPPER_CONSTRAINTS_FILE\n\n# TODO(pabelanger):\
          \ Remove once we migrated to bindep\n./openstack/diskimage-builder/tests/install_test_deps.sh\n\
          \n# This sets up some repo files pointing to the infra mirrors\n# which\
          \ are used during test runs\n./openstack/diskimage-builder/contrib/setup-gate-mirrors.sh\n\
          \n# UPPER_CONSTRAINTS_FILE is causing side effects when doing image\n# build,\
          \ unset it\nunset UPPER_CONSTRAINTS_FILE\n\n# activate the virtualenv so\
          \ that any tools run by dib run\n# using the python inside it\nset +u\n\
          source ./env/bin/activate\nset -u\n./openstack/diskimage-builder/tests/run_functests.sh\
          \ \nset +u\ndeactivate\nset -u\n"
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
