- job:
    name: base
    pre-run: base/pre
    post-run: base/post
    roles:
      - zuul: openstack-infra/openstack-zuul-roles
    success-url: http://zuulv3-dev.openstack.org/logs/{build.uuid}/
    failure-url: http://zuulv3-dev.openstack.org/logs/{build.uuid}/
    timeout: 1800
    vars:
      zuul_workspace_root: /home/zuul
    nodes:
      - name: ubuntu-xenial
        label: ubuntu-xenial

- job:
    name: tox
    parent: base
    pre-run: tox/pre
    post-run: tox/post

- job:
    name: tox-cover
    parent: tox
    run: tox/cover
    voting: false

- job:
    name: tox-docs
    parent: tox
    run: tox/docs
    post-run: tox/docs-post

- job:
    name: tox-linters
    parent: tox
    run: tox/linters

- job:
    name: tox-py27
    parent: tox
    run: tox/py27

- job:
    name: tox-py35
    parent: tox
    run: tox/py35

- job:
    name: tox-tarball
    parent: tox
    run: tox/tarball
    post-run: tox/tarball-post

- project:
    name: openstack-infra/openstack-zuul-jobs
    check:
      jobs:
        - tox-docs
        - tox-linters
