- job:
    name: openstack-doc-build
    parent: zuul-tox-docs
    run: playbooks/tox/docs

- project:
    name: openstack-infra/openstack-zuul-jobs
    check:
      jobs:
        - openstack-doc-build
        - zuul-tox-linters
