- hosts: all
  name: Autoconverted job legacy-bashate-devstack from old job gate-bashate-devstack
  tasks:

    - shell:
        cmd: /usr/local/jenkins/slave_scripts/install-distro-packages.sh
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -u
          set -e
          set -x
          cd $WORKSPACE

          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            git://git.openstack.org \
            openstack-dev/bashate \
            openstack-dev/devstack \
            openstack-infra/devstack-gate

          export BASHATE_INSTALL_PATH=$WORKSPACE/openstack-dev/bashate

          pushd openstack-dev/devstack
          tox -e bashate
          popd

          pushd openstack-infra/devstack-gate
          tox -e bashate
          popd
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
