- hosts: all
  name: Autoconverted job legacy-periodic-package-stackviz-element from old job periodic-package-stackviz-element
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          export BRANCH=master
          CLONEMAP=`mktemp`
          function cleanup {
              mkdir -p $WORKSPACE
              rm -f $CLONEMAP
          }
          trap cleanup EXIT
          cat > $CLONEMAP << EOF
          clonemap:
            - name: $ZUUL_PROJECT
              dest: .
          EOF
          /usr/zuul-env/bin/zuul-cloner -m $CLONEMAP --cache-dir /opt/git \
              --branch=$BRANCH \
              git://git.openstack.org $ZUUL_PROJECT
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: /usr/local/jenkins/slave_scripts/install-distro-packages.sh
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -x
          sudo rm -f /etc/sudoers.d/jenkins-sudo
          # Prove that general sudo access is actually revoked
          ! sudo -n true
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          # NOTE(pabelanger): Delete npm mirror, since it is currently broken.
          rm -rf ~/.npmrc
          export DISPLAY=:99
          # Because we want to publish the build folder, create an empty
          # .npmignore file.
          touch .npmignore
          npm install --verbose
          npm run prod --verbose
          mv dist/stackviz*.tar.gz dist/stackviz-latest.tar.gz
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
