- name: Get latest tag for project
  args:
    chdir: "{{ zuul_work_dir }}"
    executable: /bin/bash
  # This is a hack to ignore the year.release tags in projects since
  # now all projects use semver based versions instead of date based
  # versions. The date versions will sort higher even though they
  # should not so we just special case it here.
  shell: |
    git tag | sed -n -e '/^20[0-9]\{2\}\..*$/d' -e '/^[0-9]\+\(\.[0-9]\+\)*$/p' | sort -V | tail -1
  register: latest
  tags: skip_ansible_lint

# Put tagged releases in proper location. All tagged builds get copied to
# BUILD_DIR/tagname. If this is the latest tagged release the copy of files
# at BUILD_DIR remains. When Zuul copies this file the root developer
# docs are always the latest release with older tags available under the
# root in the tagname dir.

- name: Process tags only builds when the tag is the latest tag
  args:
    chdir: "{{ zuul_work_dir }}"
  # Now publish to / and /$TAG if this is the latest version for projects
  # and we are only publishing from the release pipeline,
  # or just /$TAG otherwise.
  shell: |
    # Copy the docs into a subdir if this is a tagged build
    mkdir doc/build/{{ zuul.tag }}
    cp -R doc/build/html/. doc/build/{{ zuul.tag }}
    mv doc/build/{{ zuul.tag }} doc/build/html/{{ zuul.tag }}
  tags: skip_ansible_lint
