- hosts: all
  roles:
    - role: fetch-tox-output
    - role: fetch-sphinx-output
      sphinx_output_src: "{{ zuul.project.src_dir }}/releasenotes/build/html/"
      zuul_executor_dest: "{{ zuul.executor.log_root }}"
