- hosts: all
  name: Autoconverted job legacy-periodic-tempest-dsvm-oslo-latest-full-master from
    old job periodic-tempest-dsvm-oslo-latest-full-master
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_NEUTRON=1
          export BRANCH_OVERRIDE=master
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          export DEVSTACK_PROJECT_FROM_GIT="oslo.cache"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.concurrency"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.config"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.context"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.db"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.i18n"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.log"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.messaging"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.middleware"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.policy"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.privsep"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.reports"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.rootwrap"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.serialization"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.service"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.utils"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.versionedobjects"
          export DEVSTACK_PROJECT_FROM_GIT+=",oslo.vmware"

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
