- hosts: all
  name: Autoconverted job legacy-glanceclient-dsvm-functional from old job gate-glanceclient-dsvm-functional-ubuntu-xenial
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export BRANCH_OVERRIDE=default
          export DEVSTACK_PROJECT_FROM_GIT=python-glanceclient
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          if [ "" == "-identity-v3-only" ] ; then
              export DEVSTACK_LOCAL_CONFIG="ENABLE_IDENTITY_V2=False"
          fi

          # TODO(rosmaita): remove when glanceclient tests no longer
          #   use the Images v1 API
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"GLANCE_V1_ENABLED=True"

          function post_test_hook {
              # Configure and run functional tests
              $BASE/new/python-glanceclient/glanceclient/tests/functional/hooks/post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
