- hosts: all
  tasks:

    - name: Copy files from deploy-guide/build/html/ on node
      synchronize:
        src: deploy-guide/build/html/
        dest: '{{ zuul.executor.log_root }}/html/'
        mode: pull
        copy_links: true
        verify_host: true
