- hosts: all
  tasks:
    - name: Ensure logs directory
      file:
        path: '{{ ansible_user_dir }}/logs'
        state: directory
        mode: 0755

    # TODO use with items
    - name: Write runtime log
      shell: |
        set -x
        journalctl -b -o short-precise -t kata-runtime | gzip > {{ ansible_user_dir }}/logs/kata-runtime.log.gz
      become: yes
    - name: Make runtime log readable
      file:
        path: '{{ ansible_user_dir }}/logs/kata-runtime.log.gz'
        mode: 'u+r,g+r,o+r'
      become: yes

    - name: Write agent and proxy log
      shell: |
        set -x
        journalctl -b -o short-precise -t kata-proxy | gzip > {{ ansible_user_dir }}/logs/kata-proxy.log.gz
      become: yes
    - name: Make proxy log readable
      file:
        path: '{{ ansible_user_dir }}/logs/kata-proxy.log.gz'
        mode: 'u+r,g+r,o+r'
      become: yes

    - name: Write shim log
      shell: |
        set -x
        journalctl -b -o short-precise -t kata-shim | gzip > {{ ansible_user_dir }}/logs/kata-shim.log.gz
      become: yes
    - name: Make shim log readable
      file:
        path: '{{ ansible_user_dir }}/logs/kata-shim.log.gz'
        mode: 'u+r,g+r,o+r'
      become: yes

    - name: Write docker log
      shell: |
        set -x
        journalctl -b -o short-precise -u docker.service | gzip > {{ ansible_user_dir }}/logs/docker.log.gz
      become: yes
    - name: Make docker log readable
      file:
        path: '{{ ansible_user_dir }}/logs/docker.log.gz'
        mode: 'u+r,g+r,o+r'
      become: yes

    - name: Write crio log
      shell: |
        set -x
        journalctl -b -o short-precise -u crio | gzip > {{ ansible_user_dir }}/logs/crio.log.gz
      become: yes
    - name: Make crio log readable
      file:
        path: '{{ ansible_user_dir }}/logs/crio.log.gz'
        mode: 'u+r,g+r,o+r'
      become: yes

    - name: Write kubelet log
      shell: |
        set -x
        journalctl -b -o short-precise -u kubelet | gzip > {{ ansible_user_dir }}/logs/kubelet.log.gz
      become: yes
    - name: Make kubelet log readable
      file:
        path: '{{ ansible_user_dir }}/logs/kubelet.log.gz'
        mode: 'u+r,g+r,o+r'
      become: yes

    - name: Copy log files from test node to executor
      synchronize:
        src: '{{ ansible_user_dir }}/logs'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --prune-empty-dirs

