- hosts: all
  tasks:
    - name: Run kata run.sh
      args:
        executable: /bin/bash
        chdir: "{{ zuul.project.src_dir }}"
      shell: |
        set -x
        if [ -d '/usr/lib/go-1.10/bin' ] ; then
            export PATH=$PATH:/usr/lib/go-1.10/bin
        fi
        export CI=true
        export GOPATH=$HOME
        .ci/run.sh
