- hosts: all
  tasks:
    - name: Send release announcement
      command: >
        src/git.openstack.org/openstack-infra/release-tools/announce.sh
          src/{{ zuul.project.canonical_name }} {{ zuul.tag }}
