- hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "src/{{ zuul.project.canonical_name }}"
    - role: bindep
      bindep_profile: test
      bindep_dir: src/opendev.org/openstack/releases
    - revoke-sudo
