- hosts: all
  roles:
    - tox

  post_tasks:

    - name: check for whereto
      stat:
        path: "{{ zuul_work_dir }}/.tox/{{ tox_envlist }}/bin/whereto"
      register: whereto

    - name: Run tox again for whereto
      include_role:
        name: tox
      vars:
        tox_extra_args: whereto doc/source/_extra/.htaccess doc/test/redirect-tests.txt
      when: whereto.stat.exists
