- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-full-lio from old job gate-tempest-dsvm-full-lio-ubuntu-xenial
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          CINDER_ISCSI_HELPER=lioadm
          CINDER_LVM_TYPE=thin
          enable_service barbican
          enable_plugin barbican git://git.openstack.org/openstack/barbican

          EOF
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PROJECTS="openstack/barbican $PROJECTS"
          export PROJECTS="openstack/python-barbicanclient $PROJECTS"
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=1
          # As we are setting DEVSTACK_GATE_TEMPEST_ALL_PLUGINS, we need to add
          # the regex to limit the tests to the same as a tempest -efull would
          # run.
          export DEVSTACK_GATE_TEMPEST_REGEX='(?!.*\[.*\bslow\b.*\])(^tempest\.(api|scenario)|(^cinder\.tests.tempest))'
          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          # If an in-repo configuration exists, source it.  This will likely
          # override DEVSTACK_GATE_TEMPEST_REGEX to further refine the set of
          # tests being run.
          if [ -f "/opt/stack/new/cinder/tests/tempest/config/lio/tempest-conf.sh" ]; then
              export DEVSTACK_GATE_SETTINGS=/opt/stack/new/cinder/tests/tempest/config/lio/tempest-conf.sh
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
