- hosts: all
  name: Autoconverted job legacy-networking-vpp-smoke from old job gate-networking-vpp-smoke-ubuntu-xenial-nv
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin networking-vpp git://git.openstack.org/openstack/networking-vpp
          Q_PLUGIN=ml2
          Q_USE_SECGROUP=True
          Q_ML2_PLUGIN_MECHANISM_DRIVERS=vpp
          Q_ML2_PLUGIN_TYPE_DRIVERS=vlan,flat
          Q_ML2_TENANT_NETWORK_TYPE=vlan
          ML2_VLAN_RANGES=physnet:100:200
          MECH_VPP_PHYSNETLIST=physnet:tap-0
          disable_service horizon
          disable_service ceilometer-acentral ceilometer-acompute
          disable_service ceilometer-alarm-evaluator
          disable_service ceilometer-alarm-notifier
          disable_service ceilometer-anotification ceilometer-api
          disable_service ceilometer-collector
          disable_service s-account s-container s-object s-proxy
          disable_service cinder c-sch c-api c-vol
          disable_service etcd3
          disable_service q-agt
          NR_HUGEPAGES=1024

          EOF
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true

          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_TEMPEST=1
          export PROJECTS="openstack/networking-vpp $PROJECTS"

          export KEEP_LOCALRC=1

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
