- name: Install make
  package:
    name: make
    state: present
  become: yes
- name: Install automake
  package:
    name: automake
    state: present
  become: yes
- name: Install gcc
  package:
    name: gcc
    state: present
  become: yes
- name: Install g++
  package:
    name: gcc-c++
    state: present
  become: yes
- name: Install golang
  package:
    name: golang
    state: present
  become: yes

# Install docker because .ci/setup.sh installs a version that is too old
# to pass CI testing with.
# TODO have .ci/setup.sh do the right thing
- name: Install dnf-plugins-core
  package:
    name: dnf-plugins-core
    state: present
  become: yes
- name: Add docker-ce repo
  args:
    executable: /bin/bash
  shell: |
    set -x
    dnf config-manager --add-repo "https://download.docker.com/linux/fedora/docker-ce.repo"
    dnf makecache
  become: yes
- name: Install docker-ce
  package:
    name: docker-ce
    state: present
  become: yes

  # TODO why isn't this necessary on Ubuntu?
- name: Ensure vhost and vhost_net modules are present as kata checks for these
  args:
    executable: /bin/bash
  shell: |
    set -x
    modprobe vhost_net
  become: yes
