- hosts: all
  tasks:
    - name: Find tox directories to synchrionize.
      find:
        file_type: directory
        paths: "{{ zuul_workspace_root }}/src/{{ zuul.project.canonical_name }}/.tox"
        # NOTE(pabelanger): The .tox/log folder is empty, ignore it.
        patterns: ^(?!log).*$
        use_regex: yes
      register: result

    - name: Collect tox logs.
      synchronize:
        dest: "{{ zuul.executor.log_root }}/tox"
        mode: pull
        src: "{{ item.path }}/log/"
      with_items: "{{ result.files }}"

    - name: Collect test-results.
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        rsync_opts:
          - "--ignore-missing-args"
        src: "{{ zuul_workspace_root }}/src/{{ zuul.project.canonical_name }}/{{ item }}"
      with_items:
        - "*testr_results.html.gz"
        - "*testrepository.subunit.gz"
