- hosts: all
  name: Autoconverted job legacy-tacker-dsvm-functional from old job gate-tacker-dsvm-functional-ubuntu-xenial-nv
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          SFC_UPDATE_OVS=False
          enable_plugin heat git://git.openstack.org/openstack/heat
          enable_plugin aodh git://git.openstack.org/openstack/aodh
          enable_plugin ceilometer https://git.openstack.org/openstack/ceilometer
          enable_plugin networking-sfc http://git.trystack.cn/openstack/networking-sfc
          enable_plugin mistral git://git.openstack.org/openstack/mistral
          enable_plugin barbican git://git.openstack.org/openstack/barbican
          enable_plugin tacker git://git.openstack.org/openstack/tacker

          EOF
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_HORIZON=1
          export DEVSTACK_GATE_TEMPEST=0
          export BRANCH_OVERRIDE=default
          export PROJECTS="openstack/tacker $PROJECTS"
          export PROJECTS="openstack/tacker-horizon $PROJECTS"
          export PROJECTS="openstack/python-tackerclient $PROJECTS"
          export PROJECTS="openstack/heat $PROJECTS"
          export PROJECTS="openstack/aodh $PROJECTS"
          export PROJECTS="openstack/ceilometer $PROJECTS"
          export PROJECTS="openstack/networking-sfc $PROJECTS"
          export PROJECTS="openstack/mistral $PROJECTS"
          export PROJECTS="openstack/mistral-dashboard $PROJECTS"
          export PROJECTS="openstack/python-mistralclient $PROJECTS"
          export PROJECTS="openstack/barbican $PROJECTS"
          export PROJECTS="openstack/python-barbicanclient $PROJECTS"

          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function post_test_hook {
              bash -xe $BASE/new/tacker/tacker/tests/contrib/post_test_hook.sh dsvm-functional
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
