- hosts: all
  tasks:

    # Note we always create the artifacts dir so that the openstack artifacts
    # publishing playbook is happy.
    - name: Ensure artifacts directory exists
      file:
        state: directory
        path: '{{ zuul.executor.work_root }}/artifacts/package-afs-centos8'
      delegate_to: localhost

    # We only build an RPM if one doesn't exist for the desired version.
    - name: Check for built RPMs
      stat:
        path: '{{ ansible_user_dir }}/rpmbuild/RPMS/x86_64'
        get_checksum: false
        get_mime: false
        get_md5: false
      register: rpms_exist

    - name: Copy RPMs back for publication
      when: rpms_exist.stat.exists
      synchronize:
        src: '{{ ansible_user_dir }}/rpmbuild/RPMS/x86_64/'
        dest: '{{ zuul.executor.work_root }}/artifacts/package-afs-centos8'
        mode: pull
        delete: true
        recursive: true
