- hosts: all
  tasks:

    - name: Ensure artifacts directory exists
      file:
        state: directory
        path: '{{ zuul.executor.work_root }}/artifacts/package-afs-centos7'
      delegate_to: localhost

    - name: Copy RPMs back for publication
      synchronize:
        src: '{{ ansible_user_dir }}/rpmbuild/RPMS/x86_64'
        dest: '{{ zuul.executor.work_root }}/artifacts/package-afs-centos7'
        mode: pull
