- hosts: all
  name: Autoconverted job legacy-logstash-filters-ubuntu-trusty from old job gate-logstash-filters-ubuntu-trusty
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            https://opendev.org opendev/system-config
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cd opendev/system-config
          ./tools/logstash-filter-test.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
