- hosts: all
  tasks:
    - name: Collect console log.
      synchronize:
        dest: "{{ zuul.executor.log_root }}"
        mode: pull
        src: "/tmp/console.log"

    - name: Publish logs.
      copy:
        dest: "/opt/zuul-logs/{{ zuul.uuid}}"
        src: "{{ zuul.executor.log_root }}/"
      delegate_to: 127.0.0.1
