- name: Configure /etc/nodepool/provider for backwards compatibility
  hosts: all
  gather_facts: no
  tasks:
    - name: Warn that /etc/nodepool/provider is deprecated
      debug:
        msg: |
          The /etc/nodepool/provider file no longer exists and is being created
          for backwards compatibility purposes. The variables provided by this
          file are now available through Ansible under hostvars['nodepool'].

    - name: Create /etc/nodepool/provider file
      copy:
        content: |
          NODEPOOL_PROVIDER={{ hostvars['nodepool']['provider'] }}
          NODEPOOL_CLOUD={{ hostvars['nodepool']['cloud'] }}
          NODEPOOL_REGION={{ hostvars['nodepool']['region'] }}
          NODEPOOL_AZ={{ hostvars['nodepool']['az'] }}
        dest: /etc/nodepool/provider
