- hosts: all
  name: Autoconverted job legacy-npm-upload from old job {name}-npm-upload
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          /usr/local/jenkins/slave_scripts/npm-tarball-upload.sh $ZUUL_SHORT_PROJECT_NAME tarballs.openstack.org
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
