- hosts: all
  name: Autoconverted job legacy-npm-upload from old job {name}-npm-upload
  tasks:

    - shell:
        cmd: |
          /usr/local/jenkins/slave_scripts/npm-tarball-upload.sh $ZUUL_SHORT_PROJECT_NAME tarballs.openstack.org
      environment: '{{ zuul | zuul_legacy_vars }}'
