- hosts: all
  name: Autoconverted job legacy-bandit-integration-python-keystoneclient from old
    job gate-bandit-integration-python-keystoneclient
  tasks:

    - shell:
        cmd: /usr/local/jenkins/slave_scripts/install-distro-packages.sh
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -u
          set -e
          set -x
          cd $WORKSPACE

          /usr/zuul-env/bin/zuul-cloner --cache-dir /opt/git \
            git://git.openstack.org \
            openstack/bandit \
            openstack/python-keystoneclient

          cd $WORKSPACE/openstack/bandit

          tox -e integration openstack python-keystoneclient \
            $WORKSPACE/openstack/python-keystoneclient
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
