- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-lxd-linuxbridge from old job gate-tempest-dsvm-lxd-linuxbridge-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin nova-lxd https://git.openstack.org/openstack/nova-lxd
          # Enable linuxbridge agent and configure physical network
          Q_AGENT=linuxbridge
          PHYSICAL_NETWORK=default

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true

          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_VIRT_DRIVER="lxd"
          export PROJECTS="openstack/nova-lxd $PROJECTS"

          # keep localrc to be able to set some vars in pre_test hook
          export KEEP_LOCALRC=1

          function pre_test_hook {
            source $BASE/new/nova-lxd/contrib/ci/pre_test_hook.sh
          }
          export -f pre_test_hook

          function post_test_hook {
            source $BASE/new/nova-lxd/contrib/ci/post_test_hook.sh
          }
          export -f post_test_hook

          export DEVSTACK_GATE_SETTINGS=/opt/stack/new/nova-lxd/devstack/tempest-dsvm-lxd-rc

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
