- hosts: primary
  tasks:

    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/cover/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs

    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/reports/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs

    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: tarballs/groups/
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/tarballs/*.tar.gz
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs

    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: tarballs/groups/
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/tarballs/*.md5
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs

    - name: Copy files from {{ ansible_user_dir }}/workspace/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: tarballs/groups/
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --include=/drupal-updates/**
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
