- hosts: all
  name: Autoconverted job legacy-shade-functional-magnum from old job gate-shade-functional-magnum-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin magnum https://git.openstack.org/openstack/magnum
          MAGNUM_GUEST_IMAGE_URL=https://tarballs.openstack.org/magnum/images/fedora-atomic-f23-dib.qcow2
          MAGNUM_IMAGE_NAME=fedora-atomic-f23-dib
          disable_service ceilometer-acentral
          disable_service ceilometer-acompute
          disable_service ceilometer-alarm-evaluator
          disable_service ceilometer-alarm-notifier
          disable_service ceilometer-anotification
          disable_service ceilometer-api
          disable_service ceilometer-collector
          disable_service horizon
          disable_service s-account
          disable_service s-container
          disable_service s-object
          disable_service s-proxy

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export SHADE_HAS_DESIGNATE=0
          export SHADE_HAS_HEAT=0
          export SHADE_HAS_MAGNUM=1
          export SHADE_HAS_NEUTRON=1
          export SHADE_HAS_SWIFT=0
          export DEVSTACK_GATE_NEUTRON=1

          export PROJECTS="openstack-infra/shade $PROJECTS"
          export PROJECTS="openstack/magnum $PROJECTS"
          export PROJECTS="openstack/python-magnumclient $PROJECTS"

          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function post_test_hook {
              $BASE/new/shade/shade/tests/functional/hooks/post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
