- hosts: all
  name: Autoconverted job legacy-tempest-neutron-dsvm-src-oslo.messaging-kafka-default
    from old job gate-tempest-neutron-dsvm-src-oslo.messaging-kafka-default-ubuntu-xenial-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_FULL=1
          export DEVSTACK_GATE_NEUTRON=1

          export PROJECTS="openstack/devstack-plugin-kafka $PROJECTS"
          export DEVSTACK_LOCAL_CONFIG="enable_plugin devstack-plugin-kafka git://git.openstack.org/openstack/devstack-plugin-kafka"

          export DEVSTACK_PROJECT_FROM_GIT="oslo.messaging"

          if [ "kafka" == "amqp1" ]; then
              # The AMQP 1.0 plugin supports a couple of different message bus configurations
              # 'hybrid' - use RabbitMQ for Notifications, qdrouterd for RPC
              # 'dual' - use qpidd for Notifications, qdrouterd for RPC
              # default: use qpidd for Notifications and for RPC
              case "default" in
                hybrid)
                    export DEVSTACK_LOCAL_CONFIG+=$'\n'"AMQP1_SERVICE=qpid-hybrid"
                    ;;
                dual)
                    export DEVSTACK_LOCAL_CONFIG+=$'\n'"AMQP1_SERVICE=qpid-dual"
                    ;;
              esac
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
