- hosts: all
  name: Autoconverted job legacy-ara-integration-openstack-ansible-func-centos-7 from
    old job gate-ara-integration-openstack-ansible-func-centos-7-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          CLONEMAP=`mktemp`
          REQS_DIR=`mktemp -d`
          function cleanup {
              rm -f $CLONEMAP
              rm -rf $REQS_DIR
          }
          trap cleanup EXIT
          cat > $CLONEMAP << EOF
          clonemap:
            - name: openstack/openstack-ansible-tests
              dest: .
            - name: openstack/requirements
              dest: $REQS_DIR
          EOF
          /usr/zuul-env/bin/zuul-cloner -m $CLONEMAP \
              --cache-dir /opt/git git://git.openstack.org \
              openstack/openstack-ansible-tests \
              openstack/requirements
          cp $REQS_DIR/upper-constraints.txt ./
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          # NOTE(mhayden): The CentOS CI image has many repositories enabled by
          # default that can cause package conflicts. We must disable all of
          # them here and only enable base, updates, and epel.
          if [[ -e /usr/bin/yum ]] && [[ -x /usr/bin/yum-config-manager ]]; then
            sudo yum-config-manager --disable \*
            sudo yum-config-manager --enable base
            sudo yum-config-manager --enable epel
            sudo yum-config-manager --enable updates
          fi
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: /usr/local/jenkins/slave_scripts/install-distro-packages.sh
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          # NOTE(mhayden): EPEL is no longer required after installing distro
          # packages with bindep. Individual roles may re-enable EPEL if they
          # need it for their package installation tasks.
          if [[ -e /usr/bin/yum ]] && [[ -x /usr/bin/yum-config-manager ]]; then
            sudo yum-config-manager --disable epel
          fi
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          # Allow Jenkins user to ssh into localhost
          ssh-keygen -f ~/.ssh/id_rsa -N ""
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          ssh-keyscan localhost >> ~/.ssh/known_hosts
          ssh-keyscan 127.0.0.1 >> ~/.ssh/known_hosts
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          /usr/local/jenkins/slave_scripts/run-tox.sh functional
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
