- hosts: all
  roles:
    - role: bindep
      bindep_profile: test
      bindep_dir: "{{ zuul_work_dir }}"
    - test-setup
    - install-nodejs
    - install-yarn
    - revoke-sudo
    - install-javascript-packages
