# Project pipeline definition for openstack-zuul-jobs
- project:
    templates:
      - publish-tox-docs-infra
    check:
      jobs:
        - openstack-infra-extra-integration-xenial
        - openstack-infra-extra-integration-bionic
        - openstack-zuul-jobs-linters
    gate:
      jobs:
        - openstack-zuul-jobs-linters
