# Project pipeline definition for openstack-zuul-jobs
- project:
    name: openstack-infra/openstack-zuul-jobs
    check:
      jobs:
        - base-integration-centos-7
        - base-integration-debian-jessie
        - base-integration-fedora-26:
            voting: false
        - base-integration-ubuntu-trusty
        - base-integration-ubuntu-xenial
        - base-integration-opensuse423
        - build-openstack-sphinx-docs
        - tox-linters
    gate:
      jobs:
        - base-integration-centos-7
        - base-integration-debian-jessie
        - base-integration-ubuntu-trusty
        - base-integration-ubuntu-xenial
        - base-integration-opensuse423
        - build-openstack-sphinx-docs
        - tox-linters
