# Project pipeline definition for openstack-zuul-jobs
- project:
    templates:
      - publish-tox-docs-infra

    check:
      jobs:
        - openafs-rpm-package-build-centos-7-x86
        - openafs-rpm-package-build-centos-8-stream-x86
        - openafs-rpm-package-build-centos-8-stream-arm64
        - openafs-rpm-package-build-centos-9-stream-x86
        - openafs-rpm-package-build-centos-9-stream-arm64
        - openstack-infra-extra-integration-xenial
        - openstack-infra-extra-integration-bionic
        - openstack-zuul-jobs-linters
        - build-wheel-cache-centos-7:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-centos-8-stream:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-centos-9-stream:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-debian-buster:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-debian-bullseye:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-xenial:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-bionic:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-focal:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
    check-arm64:
      jobs:
        - build-wheel-cache-centos-8-stream-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-centos-9-stream-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-debian-buster-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-debian-bullseye-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-bionic-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
        - build-wheel-cache-ubuntu-focal-arm64:
            files:
              - playbooks/wheel-cache
              - roles/build-wheel-cache
    gate:
      jobs:
        - openafs-rpm-package-build-centos-7-x86
        - openafs-rpm-package-build-centos-8-stream-x86
        - openafs-rpm-package-build-centos-8-stream-arm64
        - openafs-rpm-package-build-centos-9-stream-x86
        - openafs-rpm-package-build-centos-9-stream-arm64
        - openstack-zuul-jobs-linters
    promote:
      jobs:
        - openafs-rpm-package-build-promote
