- hosts: all
  name: Autoconverted job legacy-kingbird-dsvm-multiregion from old job gate-kingbird-dsvm-multiregion-ubuntu-xenial-nv
  tasks:

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export PROJECTS="openstack/kingbird $PROJECTS"
          export DEVSTACK_GATE_CONFIGDRIVE=0
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_TEMPEST=0
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=0
          export DEVSTACK_GATE_TEMPEST_REGEX="kingbird.tests.tempest"

          # Keep localrc to be able to set some vars in pre_test_hook
          export KEEP_LOCALRC=1

          # Enable multinode mode, so that the subnode(the second node)
          # will be configured to run as second region in pre_test_hook.sh
          export DEVSTACK_GATE_TOPOLOGY="multinode"

          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function gate_hook {
              bash -xe $BASE/new/kingbird/kingbird/tests/tempest/gate_hook.sh
          }
          export -f gate_hook

          function post_test_hook {
              bash -xe $BASE/new/kingbird/kingbird/tests/tempest/post_test_hook.sh
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
