- hosts: all
  name: Autoconverted job legacy-tempest-dsvm-designate-pdns4-identity-v3-only from
    old job gate-tempest-dsvm-designate-pdns4-identity-v3-only-ubuntu-xenial
  tasks:

    - shell:
        cmd: |
          [ -f /etc/nodepool/uuid ] && echo "Node UUID: $(cat /etc/nodepool/uuid)"
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true

          services=rabbit,tempest,mysql,dstat,key
          services+=,n-api,n-api-meta,n-cpu,n-cond,n-sch,n-crt
          # placement service mandatory for nova from ocata
          if [[ "stable/newton" != $ZUUL_BRANCH ]]; then
             services+=,placement-api
          fi
          services+=,g-api,g-reg
          services+=,c-sch,c-api,c-vol,c-bak
          services+=,q-svc,q-dhcp,q-meta,q-agt,q-l3

          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_ALL_PLUGINS=1
          export DEVSTACK_GATE_TEMPEST_REGEX=designate

          export DEVSTACK_LOCAL_CONFIG="enable_plugin designate git://git.openstack.org/openstack/designate"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"DESIGNATE_SERVICE_PORT_DNS=5322"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"DESIGNATE_BACKEND_DRIVER=pdns4"

          export PROJECTS="openstack/designate $PROJECTS"
          export PROJECTS="openstack/python-designateclient $PROJECTS"
          export PROJECTS="openstack/designate-dashboard $PROJECTS"
          export PROJECTS="openstack/designate-tempest-plugin $PROJECTS"

          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          if [ "-identity-v3-only" == "-identity-v3-only" ] ; then
              export DEVSTACK_LOCAL_CONFIG+=$'\n'"ENABLE_IDENTITY_V2=False"
          fi

          if [ "-identity-v3-only" == "-worker-model" ] ; then
              export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_service designate-worker designate-producer"
              export DEVSTACK_LOCAL_CONFIG+=$'\n'"disable_service designate-pool-manager designate-zone-manager"
          fi

          export OVERRIDE_ENABLED_SERVICES=$services

          if [ "-identity-v3-only" == "-postgres" ] ; then
              export DEVSTACK_GATE_POSTGRES=1
          fi

          if [ "-identity-v3-only" == "-py35" ] ; then
             export DEVSTACK_GATE_USE_PYTHON3=True
          fi

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
      environment: '{{ zuul | zuul_legacy_vars }}'
