- hosts: all
  name: Autoconverted job legacy-glance_store-dsvm-functional-cinder from old job
    gate-glance_store-dsvm-functional-cinder-ubuntu-xenial-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack-infra/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              git://git.openstack.org \
              openstack-infra/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export ENABLED_SERVICES=g-api,n-api
          export BRANCH_OVERRIDE=default
          export DEVSTACK_PROJECT_FROM_GIT=glance_store
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi

          function gate_hook {
              cd $BASE/new/glance_store/glance_store/tests/functional/hooks
              ./gate_hook.sh cinder
          }
          export -f gate_hook

          function post_test_hook {
              cd $BASE/new/glance_store/glance_store/tests/functional/hooks
              ./post_test_hook.sh cinder
          }
          export -f post_test_hook

          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
