- hosts: all
  tasks:
    # We only want to publish tar.gz file to tarballs.o.o. Find everything else
    # and delete them.
    - name: Find wheels in dist folder.
      find:
        file_type: file
        paths: "src/{{ zuul.project.canonical_name }}/dist"
        patterns: ^((?!tar\.gz).)*$
        use_regex: yes
      register: result

    - name: Delete found files that don't match *.tar.gz.
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ result.files }}"

    - name: Rename tarball to branch specific name.
      shell: "mv *.tar.gz {{ zuul.project.short_name }}-{{ zuul.branch }}.tar.gz"
      args:
        chdir: "src/{{ zuul.project.canonical_name }}/dist"
