- hosts: all
  name: infra-puppet-apply
  tasks:

    - name: Run puppet-apply test
      shell: ./tools/apply-test.sh
      args:
        chdir: "{{ zuul.projects['opendev.org/opendev/system-config'].src_dir }}"
      environment:
        PUPPET_VERSION: "{{ puppet_version | default('4') }}"
      tags:
        - skip_ansible_lint
