- hosts: primary
  tasks:

    - name: Copy files from install-guide/build/html/ on node
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/install-guide/build/html/'
        dest: '{{ zuul.executor.log_root }}/html/'
        mode: pull
        copy_links: true
        verify_host: true
